sudo: required
matrix:
  fast_finish: true
  include:
  - python: '2.7'
    env: PLATFORM=centos DISTRO=el OS_VERSION=7 DOCKER_IMAGE=twindb/backup-test:centos-7
  - python: '2.7'
    env: PLATFORM=centos DISTRO=el OS_VERSION=6 DOCKER_IMAGE=twindb/backup-test:centos-6
  - python: '2.7'
    env: PLATFORM=debian DISTRO=debian OS_VERSION=stretch DOCKER_IMAGE=twindb/backup-test:stretch
  - python: '2.7'
    env: PLATFORM=ubuntu DISTRO=ubuntu OS_VERSION=trusty DOCKER_IMAGE=twindb/backup-test:trusty
  - python: '2.7'
    env: PLATFORM=ubuntu DISTRO=ubuntu OS_VERSION=xenial DOCKER_IMAGE=twindb/backup-test:xenial
  - python: '2.7'
    env: PLATFORM=ubuntu DISTRO=ubuntu OS_VERSION=bionic DOCKER_IMAGE=twindb/backup-test:bionic
  - python: '2.7'
    env: PLATFORM=ubuntu DISTRO=ubuntu OS_VERSION=cosmic DOCKER_IMAGE=twindb/backup-test:cosmic

services:
- docker

before_install:
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
- sudo apt-get update -qq

script:
- make package

deploy:
  provider: packagecloud
  repository: main
  username: twindb
  token:
    secure: 2mGP75/yZBB0bWGjKi8aV1g5+8RUESZYIkHP+EF2XyBd5cOoBnkyiEG4+1QHjeGirpOMudZ+W/jAmhvgMfdBKnwY+78QmjLj6mBmQCulhYRjYy7rqOkikLGOzaMQN0yQx+UwxV+y+MCicBC/Z+nkOYh8+V1ftf2MP9fUZOeFmRVzznETEGQ1Q79M/Dg7Q9dvo3eZ4pwC8infgbzNFNCY5PbQnRaeDibC5eRoawTk3D0fUjyAgTdMtKwtwlTwDRCX7LYygwt6Ydr3yOh5VijicRu5lAXqPlhBq5VKBAcUMe9kZXoCm3BDL/vnKsjQMzj1pzXfLvZYxKCcguItEhQd2j/z/g9msrKu1p4ONUJ7G/8ULE39mrCave/moWIKQ38I3JkiNG3pB7Aj31qSkBfMsTJ3yJpfd9KEdOCjZBqOrHVjvqXHnTI5gNWQ5/NfEFdLmOcTWtUl9vGAAul8dmBce7ZvlELBZjhMzbu0Kjk+V5sbuMIkEcIrCKtBIeAbxXAHy7hmGg1nnmbHGmS76+eIGV6NXDb+hBCismJwTAqOeVvvYE/i9S5PVBLbNuNBqHtIkXF0Sgxn9jQHjeHCMBw0vmKbdwIn30Y4mQ+lyGfVUXi8t16LmBDBIOPULfjZkfx6xX+SghICy2sXR3aKu2JuBeaql/7SnLKN5fsG4jPT54Q=
  dist: "${DISTRO}/${OS_VERSION}"
  skip_cleanup: true
  local-dir: omnibus-twindb-xtrabackup-80/pkg

notifications:
  slack:
    secure: dKHhMOyQWZtaZZeaBgOvgk5natVRelxMcryvmjeqG/odTCfJXCD5geodYPsGLmkvA1qRdplGsGRmJnYEsUHeGTpUh3rlUd+j9iQ+pDcSD7d9EisL0lQji/DFek85NcMAXtiyNeKio5aukNXbGJT1cY4oHv/H2agk2TPC6hMKdDUk5hTpDKk4SAeHqpPYQzA5kthCCO+0y5Eh8zW5fiiH8FN+eID4FTt110bPDz3mNC4tzKExWw18dSB5m8ZxFQKQID8ZRedesBsGBdn4TMRObhjSwQOXIrV/Dif6BZjadA9MNoBvcQT6pCTmc4z0UVFR6MRVrIPwiIqaVI7jKp1ZUtVPVEa+Fui0TwRRSxPb78SCjKHc2jaVgsdxDE9Hk+0CXpZTUC4QG4+vBL0c4Ile2/qlhEXfIth6uOwzxyoNJ2zwxZarKpw3YvLKg23g7ZxfjAAGg4S8VUsNcaiSfGbSPAqQNa63KribP2Rp9/3IBNbuKwYvHyS8CxcAstTIKZkZg5BvRhDb1sv1UAyLum0qLI7e2Oz3SBAO+9ejoV5gnxl7iab89bg5XxuJiSjtcbwT3TNJ34ZdtWh/vnOjsz68DG71dK9VQ4rzg4/gpMY3YWARbKc/GTNUhBOeTtH0tmKWLEATP4VIHinu+QuBzs/9QlGqy1LhB2Ct4XkXPL3uMEk=
